language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alberto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alberto/docker-react npm run test